// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

// ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDywGQMXr59Gux3m0F-IP_UF1H9HHCdV4k',
    appId: '1:950174512076:web:6e355d205de04899f9a369',
    messagingSenderId: '950174512076',
    projectId: 'gflogin-2e46e',
    authDomain: 'gflogin-2e46e.firebaseapp.com',
    storageBucket: 'gflogin-2e46e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNG506eF1meo-l-kKObHdrnZ_346XFOcE',
    appId: '1:950174512076:android:847972221527cdedf9a369',
    messagingSenderId: '950174512076',
    projectId: 'gflogin-2e46e',
    storageBucket: 'gflogin-2e46e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh0Dj6_xMRGZbIl-6ojv5wg31tIKYhFPg',
    appId: '1:950174512076:ios:1e52c9214b833188f9a369',
    messagingSenderId: '950174512076',
    projectId: 'gflogin-2e46e',
    storageBucket: 'gflogin-2e46e.appspot.com',
    androidClientId:
        '950174512076-is6pjbp7mjm0c5qo10k0ejfbv1teboq7.apps.googleusercontent.com',
    iosClientId:
        '950174512076-52e2qb5fspg75u8hqd25nd0ad3mpd8a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh0Dj6_xMRGZbIl-6ojv5wg31tIKYhFPg',
    appId: '1:950174512076:ios:1e52c9214b833188f9a369',
    messagingSenderId: '950174512076',
    projectId: 'gflogin-2e46e',
    storageBucket: 'gflogin-2e46e.appspot.com',
    androidClientId:
        '950174512076-is6pjbp7mjm0c5qo10k0ejfbv1teboq7.apps.googleusercontent.com',
    iosClientId:
        '950174512076-52e2qb5fspg75u8hqd25nd0ad3mpd8a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
